[env:wemos_d1_r32]
platform = espressif32
; Меняем плату на стандартную для этого форм-фактора
board = esp32dev 
framework = arduino

lib_deps =
    FastLED/FastLED                                                     ; из реестра PIO
    GyverLibs/EncButton@3.6.2                                           ; из реестра PIO с версией
